version: '3'

volumes:
  pg_data:
  static_volume:
  media:

services:
  db:
    image: postgres:13.10
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
  
  backend:
    image: stanislav05/kittygram_backend
    env_file: .env
    depends_on:
      - db
    volumes:
      - static_volume:/backend_static
      - media:/app/media
  
  frontend:
    env_file: .env
    image: stanislav05/kittygram_frontend
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static_volume:/frontend_static
  
  gateway:
    image: stanislav05/kittygram_gateway
    env_file: .env  
    ports:
      - 9000:80
    volumes:
      - static_volume:/static
      - media:/media
    depends_on:
      - backend
      - frontend
